spring:
  datasource:
    username: root
    password: root@525
    url: jdbc:mysql://rm-j6cuej72vt56x2i7s.mysql.rds.aliyuncs.com/kding_newlive?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



server:
  port: 8888

person:
  sex: man
