spring:
  datasource:
    username: root_king
    password: Varian_wrynn
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc\:mysql\://127.0.0.1\:3307/content_distribution_platform?useUnicode\=true&characterEncoding\=utf-8&serverTimezone\=GMT%2B8&allowMultiQueries=true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



server:
  port: 8888

person:
  sex: man
